from django.db import models
from djangosphinx import SphinxSearch
 
# Create your models here.

class news(models.Model):
    doc_num = models.IntegerField()
    doc_text= models.TextField()
    doc_entity_set = models.TextField()
    date = models.DateTimeField()
    Topic0  = models.FloatField(null=True)
    Topic1  = models.FloatField(null=True)
    Topic2  = models.FloatField(null=True)
    Topic3  = models.FloatField(null=True)
    Topic4  = models.FloatField(null=True)
    Topic5  = models.FloatField(null=True)
    Topic6  = models.FloatField(null=True)
    Topic7  = models.FloatField(null=True)
    Topic8  = models.FloatField(null=True)
    Topic9  = models.FloatField(null=True)
    Topic10 = models.FloatField(null=True)
    Topic11 = models.FloatField(null=True)
    Topic12 = models.FloatField(null=True)
    Topic13 = models.FloatField(null=True)
    Topic14 = models.FloatField(null=True)
    Topic15 = models.FloatField(null=True)
    Topic16 = models.FloatField(null=True)
    Topic17 = models.FloatField(null=True)
    Topic18 = models.FloatField(null=True)
    Topic19 = models.FloatField(null=True)
    Topic20 = models.FloatField(null=True)
    Topic21 = models.FloatField(null=True)
    Topic22 = models.FloatField(null=True)
    Topic23 = models.FloatField(null=True)
    Topic24 = models.FloatField(null=True)
    Topic25 = models.FloatField(null=True)
    Topic26 = models.FloatField(null=True)
    Topic27 = models.FloatField(null=True)
    Topic28 = models.FloatField(null=True)
    Topic29 = models.FloatField(null=True)
    Topic30 = models.FloatField(null=True)
    Topic31 = models.FloatField(null=True)
    Topic32 = models.FloatField(null=True)
    Topic33 = models.FloatField(null=True)
    Topic34 = models.FloatField(null=True)
    Topic35 = models.FloatField(null=True)
    Topic36 = models.FloatField(null=True)
    Topic37 = models.FloatField(null=True)
    Topic38 = models.FloatField(null=True)
    Topic39 = models.FloatField(null=True)
    Topic40 = models.FloatField(null=True)
    Topic41 = models.FloatField(null=True)
    Topic42 = models.FloatField(null=True)
    Topic43 = models.FloatField(null=True)
    Topic44 = models.FloatField(null=True)
    Topic45 = models.FloatField(null=True)
    Topic46 = models.FloatField(null=True)
    Topic47 = models.FloatField(null=True)
    Topic48 = models.FloatField(null=True)
    Topic49 = models.FloatField(null=True)
    Topic50 = models.FloatField(null=True)
    Topic51 = models.FloatField(null=True)
    Topic52 = models.FloatField(null=True)
    Topic53 = models.FloatField(null=True)
    Topic54 = models.FloatField(null=True)
    Topic55 = models.FloatField(null=True)
    Topic56 = models.FloatField(null=True)
    Topic57 = models.FloatField(null=True)
    Topic58 = models.FloatField(null=True)
    Topic59 = models.FloatField(null=True)
    Topic60 = models.FloatField(null=True)
    Topic61 = models.FloatField(null=True)
    Topic62 = models.FloatField(null=True)
    Topic63 = models.FloatField(null=True)
    Topic64 = models.FloatField(null=True)
    Topic65 = models.FloatField(null=True)
    Topic66 = models.FloatField(null=True)
    Topic67 = models.FloatField(null=True)
    Topic68 = models.FloatField(null=True)
    Topic69 = models.FloatField(null=True)
    Topic70 = models.FloatField(null=True)
    Topic71 = models.FloatField(null=True)
    Topic72 = models.FloatField(null=True)
    Topic73 = models.FloatField(null=True)
    Topic74 = models.FloatField(null=True)
    Topic75 = models.FloatField(null=True)
    Topic76 = models.FloatField(null=True)
    Topic77 = models.FloatField(null=True)
    Topic78 = models.FloatField(null=True)
    Topic79 = models.FloatField(null=True)
    Topic80 = models.FloatField(null=True)
    Topic81 = models.FloatField(null=True)
    Topic82 = models.FloatField(null=True)
    Topic83 = models.FloatField(null=True)
    Topic84 = models.FloatField(null=True)
    Topic85 = models.FloatField(null=True)
    Topic86 = models.FloatField(null=True)
    Topic87 = models.FloatField(null=True)
    Topic88 = models.FloatField(null=True)
    Topic89 = models.FloatField(null=True)
    Topic90 = models.FloatField(null=True)
    Topic91 = models.FloatField(null=True)
    Topic92 = models.FloatField(null=True)
    Topic93 = models.FloatField(null=True)
    Topic94 = models.FloatField(null=True)
    Topic95 = models.FloatField(null=True)
    Topic96 = models.FloatField(null=True)
    Topic97 = models.FloatField(null=True)
    Topic98 = models.FloatField(null=True)
    Topic99 = models.FloatField(null=True)


class tnews(models.Model):
    doc_text = models.TextField()
    objects = models.Manager()
    search  = SphinxSearch(index="main")
    
